from keystoneauth1 import loading
from keystoneauth1 import session
from novaclient import client
from ..instance_maker import BaseInstanceMaker
from get_client import get_client

# This InstanceMaker class can be shared across all cloud providers
class InstanceMaker(BaseInstanceMaker):

    def __init__(self, name, cloud_init_config, auth_info, **instance_info):

        self.name = name
        self.cloud_init_config = cloud_init_config
        self.image = instance_info.pop('image')
        self.flavor = instance_info.pop('flavor')
        self.client = get_client(auth_info)

        # User data is dynamically generated by the deployment tool's plugin
        instance_info['userdata'] = cloud_init_config

        # config_drive needs to be true, but I don't want to make people
        # specify that in the config file
        instance_info['config_drive'] = True

        self.instance_info = instance_info

    def create_instance(self):
        print "Creating instance: {}".format(self.name)
        print "It should be ready soon-ish. Go grab a coffee, watch a TV show, browse the internet."
        print "Go do whatever you do to entertain yourself for about an hour or so."
        nova = self.client
        nova.servers.create(self.name,self.image, self.flavor, **self.instance_info)
