import yaml


class InstanceMaker():

    def __init__(self, name, cloud_init_config):
        """

        :param name:
        :param cloud_init_config: A string representing the yaml file generated by the deployment_tool plugin.
        """
        self.name = name
        self.cloud_init_config = cloud_init_config


    def create_instance(self):
        pass
