import yaml


class BaseInstanceMaker():

    def __init__(self, name, cloud_init_config):
        """
        :param name: The name of the instance that will be created on the cloud service provider
        :param cloud_init_config: A string representing the yaml file generated by the deployment_tool plugin.
        """
        self.name = name
        self.cloud_init_config = cloud_init_config

    # Every provider plugin must have the InstanceMaker class and the
    # create_instance function
    def create_instance(self):
        pass
