# Any extra information about the deployment tool that the main program will use needs to be in here.
# The name of the deployment tool. It must be the same as the name of the directory for this
# deployment tool in the deployment_tools directory becuase it is also used to load
# it's respective plugins
# Required by the main program
name: "openstack_ansible"

# The URL to the github repository for this deployment tool
# Required by the main program
github_repo: "https://github.com/openstack/openstack-ansible"

# What deployment scripts need to be run for an AIO to be built with this deployment tool
# Required by the openstack-ansible's plugin.
deployment_scripts:
  - "/scripts/bootstrap-ansible.sh"
  - "/scripts/bootstrap-aio.sh"
  - "/scripts/run-playbooks.sh"

# A shorthand name for the deployment tool. Must be less than 8 alphabetical characters, with no spaces
# Required by the main program
shorthand_name: "osa"

# The driver used to load options from this deployment tool
# REquired by the main program
load_options_driver: "deployment_tools.openstack_ansible.load_options_driver"

# The README explaining how to deploy an AIO with this deployment tool
readme_file: "https://raw.githubusercontent.com/openstack/openstack-ansible/master/README.rst"

# The raw file of the deployment script(s)
#deployment_scripts_links:
#  - "https://raw.githubusercontent.com/openstack/openstack-ansible/master/scripts/bootstrap-ansible.sh"
#  - "https://raw.githubusercontent.com/openstack/openstack-ansible/master/scripts/bootstrap-aio.sh"
#  - "https://raw.githubusercontent.com/openstack/openstack-ansible/master/scripts/run-playbooks.sh"

# Not all flavors have the correct amount of disk space needed to run openstack-ansible.
# Below is a list of supported flavors for each provider. The cloud_init_generator
# will check against these supported flavors. If the use doesn't provide a flavor or an
# image, the first entry in the list will be used.
# Required by the plugin
supported_flavors:
  rackspace:
    - "performance2-30"
    - "8"

# Required by the plugin
supported_images:
 rackspace:
 # Ubuntu 14.04
    - "8e7bdecd-380a-43d7-af9a-ec4f4df51dbd"
 # Ubuntu 16.04
    - "821ba5f4-712d-4ec8-9c65-a3fa4bc500f9"

description: |
  OpenStack-Ansible is an official OpenStack project which aims to deploy production environments from source in a
  way that makes it scalable while also being simple to operate, upgrade, and grow.
