# OpenStackAIOBuilder user configuration file sample
provider:
  name: "rackspace"
  auth_info:
    auth_url: "https://identity.api.rackspacecloud.com/v2.0/"
    username: "someuser"
    password: "password"
    project_id: ""
    region_name: "iad"
    auth_system: "rackspace"
  instance_info:
    instance_name: "cantu-automate"
    flavor: "8"
    image: ""
    files: ""
    key_name: ""
    admin_pass: ""



