# OpenStackAIOBuilder user configuration file sample
provider:
  name: "rackspace"
  auth_info:
    auth_url: "https://identity.api.rackspacecloud.com/v2.0/"
    username: "username"
    password: "password"
    tenant_id: ""
    project_id: ""
    region_name: ""
    auth_system: "rackspace"
  instance_info:
    image: "imagename"
    flavor: "flavor"
    key_name: "keyname"
