# OpenStackAIOBuilder user configuration file sample
# Branch of the deployment_tool to use, if not specified,
# master will be used.
branch: "stable/mitaka"
provider:
  name: "rackspace"
  auth_info:
    auth_url: "https://identity.api.rackspacecloud.com/v2.0/"
    username: "username"
    password: "password"
    tenant_id: ""
    project_id: ""
    region_name: ""
    auth_system: "rackspace"
  instance_info:
    image: "imagename"
    flavor: "flavor"
    key_name: "keyname"
# Commands that will be run before openstack is deployed
pre_deployment_commands:
  - echo "test"
  - echo "any command can go here"
  - touch examplefile
  - echo "testfile"  >> /tmp/examplefile
# Commands that will be run after openstack is deployed
post_deployment_commands:
  - git status
  - echo "test"
